INSERT INTO Books(ISBN, Publisher, DatePublished, Title, Price, Format, Pages, Image, Description) VALUES ("0061120081", "Harper Perennial Modern Classics", "1960-05-23",  "To Kill a Mockingbird", "499.00", "Paperback", "324", "model/images/0061120081.jpg", "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it, To Kill A Mockingbird became both an instant bestseller and a critical success when it was first published in 1960. It went on to win the Pulitzer Prize in 1961 and was later made into an Academy Award-winning film, also a classic. <br> <br> Compassionate, dramatic, and deeply moving, To Kill A Mockingbird takes readers to the roots of human behavior - to innocence and experience, kindness and cruelty, love and hatred, humor and pathos. Now with over 18 million copies in print and translated into forty languages, this regional story by a young Alabama woman claims universal appeal. Harper Lee always considered her book to be a simple love story. Today it is regarded as a masterpiece of American literature.");
INSERT INTO Authors (AuthorName) VALUES ("Harper Lee");
INSERT INTO BookAuthor(ISBN, AuthorId) VALUES ("0061120081", LAST_INSERT_ID());
INSERT INTO BookGenre(ISBN, Genre) VALUES ("0061120081", "General Fiction");

INSERT INTO Books(ISBN, Title, Price, Image, Description) VALUES ("0316322407", "I Am Malala", "599.50", "model/images/0316322407.jpg", "When the Taliban took control of the Swat Valley in Pakistan, one girl spoke out. Malala Yousafzai refused to be silenced and fought for her right to an education. <br> <br> In October 2012, when she was 15, Malala almost paid the ultimate price. She was shot in the head while riding the bus home from school, and few expected her to survive. <br> <br> Instead, Malala's miraculous recovery has taken her on an extraordinary journey from a remote valley in northern Pakistan to the halls of the United Nations in New York. At 16, she became a global symbol of peaceful protest and the youngest nominee ever for the Nobel Peace Prize. <br> <br> Hailed by the Associated Press for its 'arresting detail,' I AM MALALA will make readers believe in the power of one person's voice to inspire change in the world.");
INSERT INTO Authors (AuthorName) VALUES ("Malala Yousafzai");
INSERT INTO BookAuthor(ISBN, AuthorId) VALUES ("0316322407", LAST_INSERT_ID());
INSERT INTO Authors (AuthorName) VALUES ("Christina Lamb");
INSERT INTO BookAuthor(ISBN, AuthorId) VALUES ("0316322407", LAST_INSERT_ID());
INSERT INTO BookGenre(ISBN, Genre) VALUES ("0316322407", "Non-Fiction");

INSERT INTO Books(ISBN, Title, Price, Image, Description) VALUES ("0451524934", "1984", "599.00", "model/images/0451524934.jpg", "The year 1984 has come and gone, but George Orwell's prophetic, nightmarish vision in 1949 of the world we were becoming is timelier than ever. 1984 is still the great modern classic of 'negative utopia' -a startlingly original and haunting novel that creates an imaginary world that is completely convincing, from the first sentence to the last four words. No one can deny the novel's hold on the imaginations of whole generations, or the power of its admonitions -a power that seems to grow, not lessen, with the passage of time.");
INSERT INTO Authors (AuthorName, AuthorImage, AuthorDescription) VALUES ("George Orwell", "model/images/GeorgeOrwell.jpg", "Eric Arthur Blair who used the pen name George Orwell, was an English novelist, essayist, journalist and critic. His work is marked by lucid prose, awareness of social injustice, opposition to totalitarianism, and outspoken support of democratic socialism.");
INSERT INTO BookAuthor(ISBN, AuthorId) VALUES ("0451524934", LAST_INSERT_ID());
INSERT INTO BookGenre(ISBN, Genre) VALUES ("0451524934 ", "Science Fiction");
INSERT INTO BookGenre(ISBN, Genre) VALUES ("0451524934 ", "General Fiction");

INSERT INTO Books(ISBN, Title, Price, Image, Description) VALUES ("1476746583", "All the Light We Cannot See", "499.00", "model/images/1476746583.jpg", "WINNER OF THE PULITZER PRIZE <br><br>From the highly acclaimed, multiple award-winning Anthony Doerr, the beautiful, stunningly ambitious instant New York Times bestseller about a blind French girl and a German boy whose paths collide in occupied France as both try to survive the devastation of World War II. <br> <br> Marie-Laure lives with her father in Paris near the Museum of Natural History, where he works as the master of its thousands of locks. When she is six, Marie-Laure goes blind and her father builds a perfect miniature of their neighborhood so she can memorize it by touch and navigate her way home. When she is twelve, the Nazis occupy Paris and father and daughter flee to the walled citadel of Saint-Malo, where Marie-Laure's reclusive great-uncle lives in a tall house by the sea. With them they carry what might be the museum's most valuable and dangerous jewel. <br> <br> In a mining town in Germany, the orphan Werner grows up with his younger sister, enchanted by a crude radio they find. Werner becomes an expert at building and fixing these crucial new instruments, a talent that wins him a place at a brutal academy for Hitler Youth, then a special assignment to track the resistance. More and more aware of the human cost of his intelligence, Werner travels through the heart of the war and, finally, into Saint-Malo, where his story and Marie-Laure's converge.<br><br>Doerr's 'stunning sense of physical detail and gorgeous metaphors' (San Francisco Chronicle) are dazzling. Deftly interweaving the lives of Marie-Laure and Werner, he illuminates the ways, against all odds, people try to be good to one another. Ten years in the writing, a National Book Award finalist, All the Light We Cannot See is a magnificent, deeply moving novel from a writer 'whose sentences never fail to thrill' (Los Angeles Times).");
INSERT INTO Authors (AuthorName, AuthorDescription) VALUES ("Anthony Doerr", "Anthony Doerr (born 1973) is an American author of novels and short stories. He gained widespread recognition for his 2014 novel All the Light We Cannot See, which won the Pulitzer Prize for Fiction.");
INSERT INTO BookAuthor(ISBN, AuthorId) VALUES ("1476746583", LAST_INSERT_ID());
INSERT INTO BookGenre(ISBN, Genre) VALUES ("1476746583", "General Fiction");

INSERT INTO Books(ISBN, Title, Price, Image, Description) VALUES ("9580555470320", "Catcher in the Rye", "399.00", "model/images/CatcherInTheRye.jpg", "'...the first thing you'll probably want to know is where I was born and what my lousy childhood was like, and how my parents were occupied and all before they had me, and all that David Copperfield kind of crap, but I don't feel like going into it, if you want to know the truth. In the first place, that stuff bores me, and in the second place, my parents would have about two hemorrhages apiece if I told anything pretty personal about them.' <br> <br> Since his debut in 1951 as The Catcher in the Rye, Holden Caulfield has been synonymous with 'cynical adolescent. Holden narrates the story of a couple of days in his sixteen-year-old life, just after he's been expelled from prep school, in a slang that sounds edgy even today and keeps this novel on banned book lists. His constant wry observations about what he encounters, from teachers to phonies (the two of course are not mutually exclusive) capture the essence of the eternal teenage experience of alienation.");
INSERT INTO Authors (AuthorName)  VALUES ("JD Salinger");
INSERT INTO BookAuthor(ISBN, AuthorId) VALUES ("0316769177", LAST_INSERT_ID());
INSERT INTO BookGenre(ISBN, Genre) VALUES ("0316769177", "General Fiction");

INSERT INTO Books(ISBN, Title, Price, Image, Description) VALUES ("0060929871", "Brave New World", "799.50", "model/images/BraveNewWorld.jpg", "Far in the future, the World Controllers have created the ideal society. Through clever use of genetic engineering, brainwashing and recreational sex and drugs, all its members are happy consumers. Bernard Marx seems alone harbouring an ill-defined longing to break free. A visit to one of the few remaining Savage Reservations, where the old, imperfect life still continues, may be the cure for his distress... <br> <br>Huxley's ingenious fantasy of the future sheds a blazing light on the present and is considered to be his most enduring masterpiece.");
INSERT INTO Authors (AuthorName, AuthorDescription) VALUES ("Aldous Huxley", "Aldous Leonard Huxley was an English writer and one of the most prominent members of the famous Huxley family. He spent the latter part of his life in the United States, living in Los Angeles from 1937 until his death in 1963. Best known for his novels and wide-ranging output of essays, he also published short stories, poetry, travel writing, and film stories and scripts. Through his novels and essays Huxley functioned as an examiner and sometimes critic of social mores, norms and ideals. Huxley was a humanist but was also interested towards the end of his life in spiritual subjects such as parapsychology and philosophical mysticism. By the end of his life, Huxley was widely acknowledged as one of the pre-eminent intellectuals of his time.");
INSERT INTO BookAuthor(ISBN, AuthorId) VALUES ("0060929871", LAST_INSERT_ID());
INSERT INTO BookGenre(ISBN, Genre) VALUES ("0060929871", "Science Fiction");
INSERT INTO BookGenre(ISBN, Genre) VALUES ("0060929871", "General Fiction");

INSERT INTO Books(ISBN, Title, Price, Image) VALUES ("0385523904", "Nothing to Envy", "799.00", "model/images/NothingToEnvy.jpg");
INSERT INTO Authors (AuthorName) VALUES ("Barbara Demick");
INSERT INTO BookAuthor(ISBN, AuthorId) VALUES ("0385523904", LAST_INSERT_ID());
INSERT INTO BookGenre(ISBN, Genre) VALUES ("0385523904", "Non-Fiction");

INSERT INTO Books(ISBN, Title, Price, Image) VALUES ("0553381695", "A Clash of Kings", "599.00", "model/images/AClashOfKings.jpg");
INSERT INTO BookGenre(ISBN, Genre) VALUES ("0553381695", "Fantasy");
INSERT INTO BookGenre(ISBN, Genre) VALUES ("0553381695", "General Fiction");
INSERT INTO Books(ISBN, Title, Price, Image, Description) VALUES ("1066411311", "A Dance With Dragons", "599.00", "model/images/ADanceWithDragons.jpg", "In the aftermath of a colossal battle, the future of the Seven Kingdoms hangs in the balance...beset by newly emerging threats from every direction. In the east, Daenerys Targaryen, the last scion of House Targaryen, rules with her three dragons as queen of a city built on dust and death. But Daenerys has thousands of enemies, and many have set out to find her. As they gather, one young man embarks upon his own quest for the queen, with an entirely different goal in mind.<br> <br>Fleeing from Westeros with a price on his head, Tyrion Lannister, too, is making his way to Daenerys. But his newest allies in this quest are not the rag-tag band they seem, and at their heart lies one who could undo Daenerys's claim to Westeros forever.<br><br>Meanwhile, to the north lies the mammoth Wall of ice and stone - a structure only as strong as those guarding it. There, Jon Snow, 998th Lord Commander of the Night's Watch, will face his greatest challenge. For he has powerful foes not only within the Watch but also beyond, in the land of the creatures of ice.<br><br>From all corners, bitter conflicts reignite, intimate betrayals are perpetrated, and a grand cast of outlaws and priests, soldiers and skinchangers, nobles and slaves, will face seemingly insurmountable obstacles. Some will fail, others will grow in the strength of darkness. But in a time of rising restlessness, the tides of destiny and politics will lead inevitably to the greatest dance of all.");
INSERT INTO BookGenre(ISBN, Genre) VALUES ("1066411311", "Fantasy");
INSERT INTO BookGenre(ISBN, Genre) VALUES ("1066411311", "General Fiction");
INSERT INTO Books(ISBN, Title, Price, Image) VALUES ("0553573421", "A Storm of Swords", "599.00", "model/images/AStormOfSwords.jpg");
INSERT INTO BookGenre(ISBN, Genre) VALUES ("0553573421", "Fantasy");
INSERT INTO BookGenre(ISBN, Genre) VALUES ("0553573421", "General Fiction"); 
INSERT INTO Authors (AuthorName, AuthorImage, AuthorDescription) VALUES ("George RR Martin", "model/images/GeorgeRRMartin.jpg","George R. R. Martin was born September 20, 1948, in Bayonne, New Jersey. His father was Raymond Collins Martin, a longshoreman, and his mother was Margaret Brady Martin. He has two sisters, Darleen Martin Lapinski and Janet Martin Patten.");
INSERT INTO BookAuthor(ISBN, AuthorId) VALUES ("0553381695", LAST_INSERT_ID());
INSERT INTO BookAuthor(ISBN, AuthorId) VALUES ("0553573421", LAST_INSERT_ID());
INSERT INTO BookAuthor(ISBN, AuthorId) VALUES ("1066411311", LAST_INSERT_ID());

INSERT INTO Books(ISBN, Title, Price, Image) VALUES ("17470674", "Fahrenheit 451", "299.00", "model/images/17470674.jpg");
INSERT INTO Authors (AuthorName) VALUES ("Ray Bradbury");
INSERT INTO BookAuthor(ISBN, AuthorId) VALUES ("17470674", LAST_INSERT_ID());
INSERT INTO BookGenre(ISBN, Genre) VALUES ("17470674", "Science Fiction")