SET FOREIGN_KEY_CHECKS=0; 
DROP TABLE IF EXISTS Genres;
DROP TABLE IF EXISTS Reviews;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Authors;
DROP TABLE IF EXISTS BookAuthor;
DROP TABLE IF EXISTS Books;
DROP TABLE IF EXISTS FavoriteShelf;
DROP TABLE IF EXISTS ToReadShelf;
DROP TABLE IF EXISTS ReadShelf;
DROP TABLE IF EXISTS LiteraryAwards;

CREATE TABLE Users(
	FirstName VARCHAR(100) NOT NULL,
	LastName  VARCHAR(100) NOT NULL,
	Email VARCHAR(50) PRIMARY KEY,
	Password VARCHAR(256) NOT NULL,
	DateAdded DATE, 
	Country VARCHAR(50),
	Birthdate DATE
);

CREATE TABLE Books(
	ISBN VARCHAR(500) PRIMARY KEY,
	Title VARCHAR(256) NOT NULL,
	Price DECIMAL(10,2) NOT NULL,
	Publisher VARCHAR(256), 
	Description VARCHAR(5000),
	Image VARCHAR(50),
	DatePublished DATE,
	Format VARCHAR(50),
	Pages INTEGER
);

CREATE TABLE Authors(
	AuthorId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	AuthorName VARCHAR(256) NOT NULL,
	AuthorDescription VARCHAR(5000),
	Birthdate DATE,
	Country VARCHAR(50),
	Gender VARCHAR(10)
);

CREATE TABLE BookAuthor(
	ISBN VARCHAR(500) NOT NULL,
	AuthorId INT NOT NULL,
	PRIMARY KEY(ISBN, AuthorId)
);

CREATE TABLE Genres(
	ISBN VARCHAR(500) NOT NULL,
	Genre VARCHAR(50) NOT NULL,
	PRIMARY KEY(ISBN, Genre)
); 

CREATE TABLE Reviews(
	ISBN VARCHAR(500) NOT NULL, 
	Email VARCHAR(50) NOT NULL,
	Stars INT(5) NOT NULL,
	Review VARCHAR(500),
	PRIMARY KEY(ISBN, Review)
);

CREATE TABLE LiteraryAwards(
	ISBN VARCHAR(500) NOT NULL,
	Award VARCHAR(500),
	PRIMARY KEY(ISBN, Award) 
);

CREATE TABLE FavoriteShelf(
	Email VARCHAR(50) NOT NULL,
	ISBN VARCHAR(500) NOT NULL,
	PRIMARY KEY(Email, ISBN) 
);

CREATE TABLE ToReadShelf(
	Email VARCHAR(50) NOT NULL,
	ISBN VARCHAR(500) NOT NULL,
	PRIMARY KEY(Email, ISBN) 
);

CREATE TABLE ReadShelf(
	Email VARCHAR(50) NOT NULL,
	ISBN VARCHAR(500) NOT NULL,
	PRIMARY KEY(Email, ISBN) 
);

ALTER TABLE Genres ADD FOREIGN KEY (ISBN) REFERENCES Books(ISBN);
ALTER TABLE Reviews ADD FOREIGN KEY (ISBN) REFERENCES Books(ISBN);
ALTER TABLE Reviews ADD FOREIGN KEY (Email) REFERENCES Users(Email);
ALTER TABLE FavoriteShelf ADD FOREIGN KEY(Email) References Users(Email);
ALTER TABLE FavoriteShelf ADD FOREIGN KEY(ISBN) References Books(ISBN);
ALTER TABLE BookAuthor ADD FOREIGN KEY(ISBN) References Books(ISBN);
ALTER TABLE BookAuthor ADD FOREIGN KEY(AuthorId) References Authors(AuthorId)